# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release canary

on:
  push:
    branches: [master]
    paths-ignore: 
      - "**/package.json"

jobs:
  releases:
    name: Release
    
    runs-on: ubuntu-latest

    env:
      CI: true
      NPM_AUTH_TOKEN: ${{ secrets.NPMJS_ORG_PUBLISHER_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ROBBY_ATWEELS_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure git user name & email
        run: |
          git config --global user.email "robby@atweel.com" && \
          git config --global user.name "Robby Atweel"

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Resolve yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Save/restore yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Release package(s)
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" > .npmrc && \
          yarn install --frozen-lockfile && \
          yarn lerna bootstrap -- -- --frozen-lockfile && \
          yarn release:canary --yes
